#!/bin/sh

# EXAMPLE SCRIPT OF GRABBING A SIGNAL FROM A SINGLE FREQUENCY
# AND THEN PROCESSING IT

RECEIVE_DURATION=15
RF_GAIN=32
FREQUENCY=103.0

python receive.py -g $RF_GAIN -f $FREQUENCY -t $RECEIVE_DURATION
python3 demod.py
