#!/bin/sh

# EXAMPLE SCRIPT OF GRABBING A SIGNAL FROM A SINGLE FREQUENCY
# AND THEN PROCESSING IT

cd "$(dirname $0)"

RECEIVE_DURATION=15
RF_GAIN=35
FREQUENCY=106.1

python receive.py -g $RF_GAIN -f $FREQUENCY -t $RECEIVE_DURATION
python3 demod.py
